### ISSUE TITLE
Bug with small images not working perfectly in Safari

### ISSUE THREAD

**Issue by iJungleboy** [2sic/dnn-imageflow#2]
https://github.com/2sic/2sxc/issues/3111

**Comment by tvatavuk** [comment]
Issue reproduced. 

1. Tested with image: https://2sxc-dnn.dnndev.me/Portals/0/images/2sxc.jpg

2. Small image is not working in Safari: https://2sxc-dnn.dnndev.me/Portals/0/images/2sxc.jpg?w=100
   <img width="1440" alt="not-working-without-fix" src="https://github.com/2sic/dnn-imageflow/assets/2724850/90f8bea1-64b0-4985-b85a-e7041ee14d54">

3. After fix, small image is working in Safari: https://dnn-imageflow.dnndev.me/Portals/0/images/2sxc.jpg?w=100
   <img width="1440" alt="working-with-fix" src="https://github.com/2sic/dnn-imageflow/assets/2724850/635d8ffe-2e3e-4ee9-86d2-393bdd95a261">
